### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kcastrotech** [CumberlandGroup/node-ews#17] opened 2016-09-02 20:29 UTC
I'm running EWS function "UpdateItem" with arguments:

```
{
    attributes: {
        MessageDisposition: 'SaveOnly',
        ConflictResolution: 'AutoResolve'
    },
    ItemChanges: [{
        ItemChange: {
            ItemId: {
                attributes: {
                    Id: 'ATAUAGxsaW5kaGFyZHRAY2Jja2Mub3JnAEYAAAAAAI4eNWlSRatInnhuyOcnSIcHAPfFMAPpnn1HvotUdVcL/eIAAACqgs0AAImAA2RsA2BBpnhjzIcvvcEAANKuJAUAAA==',
                    ChangeKey: 'EwNAABYAAACJgANkbANgQaZ4Y8yHL73BAAFT2pmM'
                }
            },
            Updates: {
                SetItemField: {
                    FieldURI: {
                        attributes: {
                            FieldURI: "item:Categories"
                        },
                        Task: {
                            Categories: {
                                'String': ['Urgent!', 'Important!']
                            }
                        }
                    }
                }
            }
        }
    }]
}
```

and I'm getting:

> C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1838
> WSDL.prototype.findChildSchemaObject = function(parameterTypeObj, childName) {
>                                                ^
> 
> RangeError: Maximum call stack size exceeded
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1838:48)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1881:19)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1881:19)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)

**Comment by nmarus** [comment] 2016-09-03 17:59
"Maximum call stack size exceeded" is related to Node JS limiting recursive depth. While this can be increased, I believe this is related to the query structure you are using not matching the types of the elements. I'm looking at options to add some sort of validation and error notification to better handle this, but this is happening inside the soap library, so not sure on how to attack that yet. 

For reference:

"Updates" is an array - https://msdn.microsoft.com/en-us/library/office/aa581081.aspx
"Categories" is an array - https://msdn.microsoft.com/en-us/library/office/aa563930.aspx
"String" is not - https://msdn.microsoft.com/en-us/library/office/aa565988.aspx

The query probably should look like this:

```js
{
  'attributes': {
    'MessageDisposition': 'SaveOnly',
    'ConflictResolution': 'AutoResolve'
  },
  // https://msdn.microsoft.com/en-us/library/office/aa565428.aspx
  'ItemChanges': [{
    // https://msdn.microsoft.com/en-us/library/office/aa581081.aspx
    'ItemChange': {
      // https://msdn.microsoft.com/en-us/library/office/aa580234.aspx
      'ItemId': {
        'attributes': {
          'Id': 'ATAUAGxsaW5kaGFyZHRAY2Jja2Mub3JnAEYAAAAAAI4eNWlSRatInnhuyOcnSIcHAPfFMAPpnn1HvotUdVcL/eIAAACqgs0AAImAA2RsA2BBpnhjzIcvvcEAANKuJAUAAA==',
          'ChangeKey': 'EwNAABYAAACJgANkbANgQaZ4Y8yHL73BAAFT2pmM'
        }
      },
      // https://msdn.microsoft.com/en-us/library/office/aa581074.aspx
      'Updates': [
        // https://msdn.microsoft.com/en-us/library/office/aa581487.aspx
        'SetItemField': {
          // https://msdn.microsoft.com/en-us/library/office/aa494315.aspx
          'FieldURI': {
            'attributes': { 'FieldURI': 'item:Categories' }
          },
          // https://msdn.microsoft.com/en-us/library/office/aa563930.aspx
          'Task': {
            // https://msdn.microsoft.com/en-us/library/office/aa580790.aspx
            'Categories': [
              // https://msdn.microsoft.com/en-us/library/office/aa565988.aspx
              { String: 'Urgent!' },
              { String: 'Important!' }
            ]
          }
        }
      ]
    }
  }]
}
```

**Comment by kcastrotech** [comment] 2016-09-04 03:31
Good catch on the structure. In the FindItem response, String is an array so I'd just assumed it would be in the update request too. However, even after correcting it as suggested I'm still getting the same error, albeit in a different spot:

> C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:64
>   {prefix: nsName.substring(0, i), name: nsName.substring(i + 1)};
>                                                 ^
> 
> RangeError: Maximum call stack size exceeded
>     at String.substring (native)
>     at splitQName (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:64:49)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1873:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1881:19)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)
>     at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\soap\lib\wsdl.js:1887:20)

**Comment by nmarus** [comment] 2016-09-04 04:50
Unfortunately that error happens when processing a large array. It's a known issue with node-soap and with any node app that uses a recursive function to process a large array/collection. The default stack size is 984. Try increasing the stack size and see if runs. `node --stack_size 10000 app.js`

**Comment by kcastrotech** [comment] 2016-09-06 16:16
Now the app just terminates without any errors but without completing the script.

**Comment by nmarus** [comment] 2016-09-07 00:20
Does the console output anything? Try running `DEBUG=* node --stack_size 10000 app.js` and see if the soap debugs shed anymore light on the issue.

**Comment by kcastrotech** [comment] 2016-09-09 05:21
It terminated without any errors, it just never gets to the .then chain.

And  "DEBUG=*" doesn't work as "'DEBUG' is not recognized as an internal or external command'...  I'm running this on a Windows 10 box so that's probably why.

**Comment by nmarus** [comment] 2016-09-09 12:15
In Windows, from your terminal run:

```
set DEBUG=*
node --stack_size 10000 app.js 
```

**Comment by kcastrotech** [comment] 2016-09-12 13:24
Same thing. Here's the output:
```
C:\leankit-exchanger>node --stack-size=100000 exchanger.js
Initializing LeanKit Exchanger
Running EWS function "FindFolder" with arguments: { attributes: { Traversal: 'Deep' },
  FolderShape: { BaseShape: 'Default' },
  ParentFolderIds: { DistinguishedFolderId: { attributes: [Object] } } }
  node-soap Reading file: C:\Users\User\AppData\Local\Temp\tmp-110327EGxEK1dVUyu\services.wsdl +0ms
  node-soap Reading file: C:\Users\User\AppData\Local\Temp\tmp-110327EGxEK1dVUyu\messages.xsd +177ms
  node-soap Reading file: C:\Users\User\AppData\Local\Temp\tmp-110327EGxEK1dVUyu\types.xsd +103ms
XML: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:tns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion></soap:Header><soap:Body><FindFolder Traversal="Deep" xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"><tns:FolderShape><t:BaseShape xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">Default</t:BaseShape></tns:FolderShape><tns:ParentFolderIds><t:DistinguishedFolderId Id="tasks" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"></t:DistinguishedFolderId></tns:ParentFolderIds></FindFolder></soap:Body></soap:Envelope>
EWS FindFolder Response: { FindFolderResponseMessage:
   { attributes: { ResponseClass: 'Success' },
     ResponseCode: 'NoError',
     RootFolder: { attributes: [Object], Folders: [Object] } } }
taskFolders: [ { FolderId: { attributes: [Object] },
    DisplayName: 'Backlog',
    TotalCount: '14',
    ChildFolderCount: '0',
    UnreadCount: '0' },
  { FolderId: { attributes: [Object] },
    DisplayName: 'Done',
    TotalCount: '100',
    ChildFolderCount: '0',
    UnreadCount: '0' },
  { FolderId: { attributes: [Object] },
    DisplayName: 'InProgress',
    TotalCount: '0',
    ChildFolderCount: '0',
    UnreadCount: '0' },
  { FolderId: { attributes: [Object] },
    DisplayName: 'Kanban View',
    TotalCount: '0',
    ChildFolderCount: '0',
    UnreadCount: '0' },
  { FolderId: { attributes: [Object] },
    DisplayName: 'LeanKit',
    TotalCount: '0',
    ChildFolderCount: '0',
    UnreadCount: '0' } ]
Running EWS function "FindItem" with arguments: { attributes: { Traversal: 'Shallow' },
  ItemShape: { BaseShape: 'IdOnly' },
  ParentFolderIds: { DistinguishedFolderId: { attributes: [Object] } } }
XML: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:tns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion></soap:Header><soap:Body><FindItem Traversal="Shallow" xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"><tns:ItemShape><t:BaseShape xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">IdOnly</t:BaseShape></tns:ItemShape><tns:ParentFolderIds><t:DistinguishedFolderId Id="tasks" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"></t:DistinguishedFolderId></tns:ParentFolderIds></FindItem></soap:Body></soap:Envelope>
EWS FindItem Response: { FindItemResponseMessage:
   { attributes: { ResponseClass: 'Success' },
     ResponseCode: 'NoError',
     RootFolder: { attributes: [Object], Items: [Object] } } }
Running EWS function "UpdateItem" with arguments: { attributes:
   { MessageDisposition: 'SaveOnly',
     ConflictResolution: 'AutoResolve' },
  ItemChanges: { ItemChange: { ItemId: [Object], Updates: [Object] } } }

C:\leankit-exchanger>
```
It just dies before ever submitting the request.

Here's the output again with DEBUG=* but not altering the stack size:

```
C:\leankit-exchanger>node exchanger.js
Initializing LeanKit Exchanger
Running EWS function "FindFolder" with arguments: { attributes: { Traversal: 'Deep' },
  FolderShape: { BaseShape: 'Default' },
  ParentFolderIds: { DistinguishedFolderId: { attributes: [Object] } } }
  node-soap Reading file: C:\Users\User\AppData\Local\Temp\tmp-3528GzWCtUOHRVe5\services.wsdl +0ms
  node-soap Reading file: C:\Users\User\AppData\Local\Temp\tmp-3528GzWCtUOHRVe5\messages.xsd +187ms
  node-soap Reading file: C:\Users\User\AppData\Local\Temp\tmp-3528GzWCtUOHRVe5\types.xsd +138ms
XML: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:tns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion></soap:Header><soap:Body><FindFolder Traversal="Deep" xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"><tns:FolderShape><t:BaseShape xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">Default</t:BaseShape></tns:FolderShape><tns:ParentFolderIds><t:DistinguishedFolderId Id="tasks" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"></t:DistinguishedFolderId></tns:ParentFolderIds></FindFolder></soap:Body></soap:Envelope>
EWS FindFolder Response: { FindFolderResponseMessage:
   { attributes: { ResponseClass: 'Success' },
     ResponseCode: 'NoError',
     RootFolder: { attributes: [Object], Folders: [Object] } } }
taskFolders: [ { FolderId: { attributes: [Object] },
    DisplayName: 'Backlog',
    TotalCount: '14',
    ChildFolderCount: '0',
    UnreadCount: '0' },
  { FolderId: { attributes: [Object] },
    DisplayName: 'Done',
    TotalCount: '100',
    ChildFolderCount: '0',
    UnreadCount: '0' },
  { FolderId: { attributes: [Object] },
    DisplayName: 'InProgress',
    TotalCount: '0',
    ChildFolderCount: '0',
    UnreadCount: '0' },
  { FolderId: { attributes: [Object] },
    DisplayName: 'Kanban View',
    TotalCount: '0',
    ChildFolderCount: '0',
    UnreadCount: '0' },
  { FolderId: { attributes: [Object] },
    DisplayName: 'LeanKit',
    TotalCount: '0',
    ChildFolderCount: '0',
    UnreadCount: '0' } ]
Running EWS function "FindItem" with arguments: { attributes: { Traversal: 'Shallow' },
  ItemShape: { BaseShape: 'IdOnly' },
  ParentFolderIds: { DistinguishedFolderId: { attributes: [Object] } } }
XML: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:tns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion></soap:Header><soap:Body><FindItem Traversal="Shallow" xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"><tns:ItemShape><t:BaseShape xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">IdOnly</t:BaseShape></tns:ItemShape><tns:ParentFolderIds><t:DistinguishedFolderId Id="tasks" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"></t:DistinguishedFolderId></tns:ParentFolderIds></FindItem></soap:Body></soap:Envelope>
EWS FindItem Response: { FindItemResponseMessage:
   { attributes: { ResponseClass: 'Success' },
     ResponseCode: 'NoError',
     RootFolder: { attributes: [Object], Items: [Object] } } }
Running EWS function "UpdateItem" with arguments: { attributes:
   { MessageDisposition: 'SaveOnly',
     ConflictResolution: 'AutoResolve' },
  ItemChanges: { ItemChange: { ItemId: [Object], Updates: [Object] } } }
C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:62
  var i = typeof nsName === 'string' ? nsName.indexOf(':') : -1;
                                              ^

RangeError: Maximum call stack size exceeded
    at splitQName (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:62:47)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1873:20)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1887:20)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1887:20)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1881:19)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1887:20)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1887:20)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1887:20)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1887:20)
    at WSDL.findChildSchemaObject (C:\leankit-exchanger\node_modules\node-ews\node_modules\soap\lib\wsdl.js:1881:19)

C:\leankit-exchanger>
```

**Comment by nmarus** [comment] 2016-09-13 00:11
Definetly seems to be related with the UpdateItem call. It looks like you are processing three calls FindFolder, FindItem, UpdateItem? If it just exits with no error, have you looked at the system log to see if there is any additional info there? Or tried running the code through a debugger such as node-inspector? Id be curious to see what node-insector shows as the last function it is hitting as it almost seems it is exiting cleanly, though without sending the last request.

**Comment by kcastrotech** [comment] 2016-09-13 00:37
Yes, I'm getting the folder structure of the Tasks folder, retrieving the tasks in the Tasks folder, then I'm trying to update the categories on those items.

No I haven't checked the system logs but it won't hurt to see.

Also, I'm very new to Node so I'm not familiar with debugging tools for it, but I'll give node-inspector a try and see what that reveals then pass on what I find. Thanks for your help!

**Comment by ng-marcus** [comment] 2016-09-19 08:58
I'm getting the same, as soon as I introduce an array,

`{
  'attributes': {
    'SendMeetingInvitations': 'SendToNone'
  },
  'Items': []
}`

generates the same overflow.

**Comment by nmarus** [comment] 2016-09-19 16:52
This should be fixed once this PR gets merged with node-soap: https://github.com/vpulim/node-soap/pull/855

**Comment by aaroncalderon** [comment] 2016-10-18 22:04
I can confirm that this issue will be fixed with tje PR vpulim/node-soap#855. I copied the contents of `wsdl.js` to my copy on `node_modules` folder and this error went away.

**Comment by Sarkar** [comment] 2016-10-28 21:27
I'm unfortunately dealing with the same issue, but copying and pasting #855 above doesn't help. Oddly enough, I have a pretty straight forward XML structure as well:

```
      <UpdateRequest xmlns="http://exacttarget.com/wsdl/partnerAPI">
         <Options/>
         <Objects xsi:type="ns1:Email" xmlns:ns1="http://exacttarget.com/wsdl/partnerAPI">
            <ID>12345</ID>           
            <Subject>UPDATED SUBJECT LINE</Subject>
            <HTMLBody><![CDATA[<html><body><table><tr><td>UPDATED BODY CONTENT</td></tr></table></br><a href="http://www.example.com">UPDATED BODY LINK<a/></br>ADDITIONAL UPDATED BODY CONTENT</body></html>]]></HTMLBody>
         </Objects>
      </UpdateRequest>
```

Which I use xml2js to turn into an object that I pass through the SOAP Client for my WSDL file. When I run w/ the bigger stack size, I end up getting a segmentation fault, and never reach the call to update, either. 

Any other suggestions?

**Comment by Sarkar** [comment] 2016-10-28 21:28
Oops, I realized I should've posted this in `node-soap` - sorry guys.

**Comment by nmarus** [comment] 2016-11-27 06:58
Integrated modified fork of node-soap into v3.0.1. Leaving this issue open until a better fix is possible.

**Comment by evan-mcclaugherty** [comment] 2017-01-13 15:57
hello, i'm experiencing the same thing with marketing cloud soap right now. However, it is weird to me the error is coming from the catch before I ever try to call the method:

```
clientPromise.then(client => {
    client.on('request', e => {
        console.log(e)
    });
    client.Create(args, function (err, result) {
        // console.log(err);
        console.log(result);
    });
}).catch(err => {
    console.log(err);  <-------------------- Error being logged here
});
```
 Retrieve and Describe work just fine except for Create. If I leave any args out, It builds the CreateRequest with an xmlns as seen just fine from inspecting the client.on('request') but as soon as i add anything at all in argumentsl i get the maximum callstack exceeded error.

```
var args = {
    Objects: [{
        attributes: {
            'xsi:type': 'AccountUser'
        },
        Client: {
            ID: 6292574
        },
        Name: "whywontthiswork",
        Email: "email@email.com",
        UserID: "whywontthiswork",
        Password: "onestrongpassword",
        DefaultBusinessUnit: 1234
    }],
};
```

RangeError: Maximum call stack size exceeded at WSDL.findChildSchemaObject (/Users/evanmcclaugherty/Documents/soap/soapVpulim/node_modules/soap/lib/wsdl.js:1924:48)

I've tried increasing the stack size too and that didn't work.  Can you shed any insight into this please?

**Comment by nmarus** [comment] 2017-01-14 02:33
The above code snippet seems references the node-soap library. The `client` object of node-soap is not exposed with node-ews nor is is the event emitter 'request'. This repo is for node-ews which uses node-soap. Did you intend to post this comment to vpulim/node-soap? 

If so, the error you are experiencing, and as discussed above, is related to the way node-soap parses Exchange Web Services WSDL which causes an infinite loop based on the recursive function at line 1924. The node-ews library is using a temporary fix to address issue 855 in vpulim/node-soap. 

This modified fork of node-soap 0.17.0 with the fix for this is found here:
https://github.com/CumberlandGroup/node-soap (https://github.com/CumberlandGroup/node-soap/commit/aafad446344ef858d424126061287376893edc8e)

**Comment by evan-mcclaugherty** [comment] 2017-01-16 15:44
Thank you so much for responding.  I apologize yes this is for node-soap. I installed the modified fork but still having the same issue with a little more debug info than last time.  I mentioned it in my last comment but do you think the problem is with the salesforce marketing cloud wsdl?

https://webservice.s6.exacttarget.com/etframework.wsdl 

```
RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at RegExp.[Symbol.match] (native)
    at String.match (native)
    at WSDL.findChildSchemaObject (/Users/evanmcclaugherty/Documents/soap/soapVpulim/node_modules/soap/lib/wsdl.js:1966:23)
```

I think i just have to resort to raw xml building.  Do you know of any alternatives or a soap library I can just just build my own requests in if this doesn't work?

Thank you

**Comment by nmarus** [comment] 2017-01-29 15:07
The fix only applies to node-soap's use with exchange wsdl files. Take a look at the [diff](https://github.com/CumberlandGroup/node-soap/commit/aafad446344ef858d424126061287376893edc8e) and you might be able to craft a fix for your error. The problem is how node-soap does recursive functions. A better fix (from what I can tell) would require implementing something like 'next tick' between recursive iterations to flush stack. This is my guess as to why vpulim/node-soap#855 has not been merged as it is more of a hack for microsoft wsdl specifically, and doesn't fix the root problem. At the moment, our fix is just breaking the recursive functions specific to microsoft ns child URIs.

**Comment by kcastrotech** [comment] 2017-04-17 15:31
Until this is fixed, I have just been manually assigning the message "m:" and type "t:" to the ewsArgs like this:
```
ews.run("FindItem",
	{
		Restriction:{
			"t:And":{
				"t:IsEqualTo":{
					"t:FieldURI":{attributes:{FieldURI:"item:ItemClass"}},
					"t:FieldURIOrConstant":{
						"t:Constant":{attributes:{Value:"IPM.Sharing"}}
					}
				}
			}
		},
		ParentFolderIds:{DistinguishedFolderId:{attributes:{Id:"inbox"}}}
	}
)
```

**Comment by nmarus** [comment] 2017-08-05 21:02
The node-soap library has fixed the recursion error. Reverted to node-soap 19.2.

**Closed by nmarus** 2017-08-05 21:02 UTC
Labels: investigating, possible bug

**Comment by kcastrotech** [comment] 2017-10-25 18:07
Using PR #69 I was able to get this working:
```
ews.run("UpdateItem", {
  'attributes': {
    'MessageDisposition': 'SaveOnly',
    'ConflictResolution': 'AutoResolve'
  },
  // https://msdn.microsoft.com/en-us/library/office/aa565428.aspx
  'ItemChanges': [{
    // https://msdn.microsoft.com/en-us/library/office/aa581081.aspx
    'ItemChange': {
      // https://msdn.microsoft.com/en-us/library/office/aa580234.aspx
      'ItemId': {
        'attributes': {
	  'Id':'AAAUAGxsaW5kaGFyZHRAY2Jja2Mub3JnAEYAAAAAAI4eNWlSRatInnhuyOcnSIcHAPfFMAPpnn1HvotUdVcL/eIAAACqgs0AAImAA2RsA2BBpnhjzIcvvcEAAkxivXAAAA==',
	  'ChangeKey':'EwAAABYAAACJgANkbANgQaZ4Y8yHL73BAAJM1b6D'
        }
      },
      // https://msdn.microsoft.com/en-us/library/office/aa581074.aspx
      'Updates': [
        // https://msdn.microsoft.com/en-us/library/office/aa581487.aspx
        {'SetItemField': {
          // https://msdn.microsoft.com/en-us/library/office/aa494315.aspx
          'FieldURI': {
            'attributes': { 'FieldURI': 'item:Categories' }
          },
          // https://msdn.microsoft.com/en-us/library/office/aa563930.aspx
          'Task': {
            // https://msdn.microsoft.com/en-us/library/office/aa580790.aspx
            'Categories': {
              // https://msdn.microsoft.com/en-us/library/office/aa565988.aspx
              'String': ['Urgent!','Important!']
            }
          }
        }}
      ]
    }
  }]
});
```
